services:

  webserver:
    build:
      context: ./webserver
      dockerfile: dockerfile
    container_name: webserver
    ports:
        - "8000:80"
        - "4443:443"
    networks:
      - Container_network
    restart: always

  back:
    build:
     context: ./back
     dockerfile: dockerfile
    container_name: back
    env_file:
      - ./back/.env
    secrets:
      - db_password
    networks:
      - Container_network
    depends_on:
      postgresql:
        condition: service_healthy
    restart: always

# enlever plus tard les ports d'acces
  postgresql:
    build:
      context: ./database
      dockerfile: dockerfile
    container_name: postgresql
    ports:
      - "127.0.0.1:5432:5432"
    env_file:
      - ./back/.env
    secrets:
      - db_password
    networks:
      - Container_network
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "GoodCorner"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - postgresql_data:/var/lib/postgresql
    restart: always

networks:
  Container_network:
    driver: bridge
secrets:
  db_password:
    file: ./.secrets/password.txt
volumes:
  postgresql_data:
