FROM node:26-alpine AS builder

WORKDIR /app

COPY package*.json ./
COPY tsconfig.json ./
RUN npm install

COPY src ./src
RUN npm run build

RUN mkdir -p ./dist/prisma/generated && cp -r ./src/prisma/generated/* ./dist/prisma/generated

FROM node:26-alpine AS runner

WORKDIR /app

COPY ./conf/back_setup.sh /usr/local/bin/back_setup.sh
RUN chmod +x /usr/local/bin/back_setup.sh

COPY package*.json ./

COPY --from=builder /app/node_modules ./node_modules
COPY --from=builder /app/dist ./dist
COPY src/prisma/schema.prisma /app/dist/prisma/


RUN mkdir -p /app/uploads

ENTRYPOINT ["/usr/local/bin/back_setup.sh"]
CMD ["npm", "start"]