FROM docker.io/library/postgres:alpine

# COPY ./conf/postgresql.conf /etc/postgresql/postgresql.conf
# copy my PostgreSQL configuration to the PostgreSQL configuration file in the docker container

COPY ./conf/db_setup.sh /usr/local/bin/db_setup.sh
RUN chmod +x /usr/local/bin/db_setup.sh
	#give associated binary execution right
ENTRYPOINT ["/usr/local/bin/db_setup.sh"]
	# launch service in foreground (PREVENT SHUTDOWN) -g for global directives
