FROM debian:bookworm
	# get docker image from dockerhub (debian penultimate release)

RUN apt update && apt upgrade -y && \
	apt install -y nginx procps && \
	rm -rf /var/lib/apt/lists/*
	# install essentials packages and wipe package library for space

COPY ./conf/nginx.conf /etc/nginx/nginx.conf
	# copy my nginx configuration to the nginx configuration file in the docker container

RUN mkdir -p /var/www/html && \
	echo "<h1>Hello from Nginx !</h1>" > /var/www/html/index.html
EXPOSE 8080
EXPOSE 9090
	#expose port 443 (https)

CMD [ "nginx", "-g", "daemon off;" ]
	# launch service in foreground (PREVENT SHUTDOWN) -g for global directives
