events 
{
	worker_connections 1024;
}

http 
{
	include /etc/nginx/mime.types;
	default_type application/octet-stream;

	server 
	{
		# listen 443; need ssl certificates
		listen 80;
		server_name TheGoodCorner, localhost;

		root /usr/share/nginx/html/app;
		index index.html;

		# fallback: si le fichier n'existe pas, serve index.html
        location / {
            try_files $uri @index;
        }

        location @index {
            rewrite ^(.*)$ /index.html break;
            add_header Cache-Control "no-cache, no-store, must-revalidate";
            add_header Pragma "no-cache";
            add_header Expires "0";
        }

		location /images 
		{
			autoindex on;
		}
		location /delete-path 
		{
			dav_methods DELETE;
		}
	}
}