events 
{
    worker_connections 1024;
}

http 
{
    include /etc/nginx/mime.types;
    default_type application/octet-stream;

    server 
    {
        listen 80;
        server_name TheGoodCorner localhost;

        root /usr/share/nginx/html/app;
        index index.html;
        port_in_redirect off;


        # 1. API Route (Separate, un-nested block)
        # Matching /products allows requests with or without trailing slash
        location /products {
            # Using a variable forces Nginx to resolve 'back' dynamically at runtime
            proxy_pass http://back:3000;

            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection 'upgrade';
            proxy_set_header Host $http_host;
            proxy_cache_bypass $http_upgrade;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }

        # 2. Uploads static directory (Serves uploaded files directly)
        location /uploads {
            set $upstream_back http://back:3000;
            proxy_pass $upstream_back;
        }

        # 3. Frontend SPA Location
        location / {
            try_files $uri $uri/ @index;
        }

        location @index {
            rewrite ^(.*)$ /index.html break;
            add_header Cache-Control "no-cache, no-store, must-revalidate";
            add_header Pragma "no-cache";
            add_header Expires "0";
        }

        location /images {
            autoindex on;
        }

        location /delete-path {
            dav_methods DELETE;
        }
    }
}