name: CD_Action

on:
  workflow_run:
    workflows: ["CI_Action"]
    types:
      - completed
    branches:
      - main
      # a voir si on garde le filtre branch main ou sur toute les branches

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
  
    steps:
      - name: checkout-code
        uses: actions/checkout@v6
        with:
          ref: ${{ github.event.workflow_run.head_sha }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Test Docker Compose Build
        run: docker compose build

      - name: Deploy APP
        run: |
          echo "execute deployment command here"
      # env
