name: CI_Action

on:
  push:
    branches:
      - main 
      # a voir si on garde le filtre branch main ou sur toute les branches

jobs:
  verify-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Set up Node.js
        uses: actions/setup-node@v6

      - name: Install back dependencies
        run: npm ci
        working-directory: ./back/NodeJS
      
      - name: Install front dependencies
        run: npm ci
        working-directory: ./webserver/app

      - name: Typecheck & build frontend
        run: |
          npx tsc --noEmit
          npm run build
        working-directory: ./webserver/app
